on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test CI
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2-beta
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: yarn
      - run: yarn test